[project]
type = "catalog"
name = "ChartBook Catalog"
maintainer = "Jeremy Bejarano"
copyright = "2025"
logo = "./logo.png"

[pipelines."backofficedev/fred_charts"]
path = "../fred_charts"

[pipelines."backofficedev/yield_curve"]
path = "../yield_curve"
